### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by ghost** [impiaaa/mastodon_import_emoji#1]
Or maybe I'm just a fool, but where is this supposed to be executed from? 

I made a folder in /live for it and ran from there and got "bundler command not found: rails" even after bundle install completed successfully.

Am I supposed to just plog the .rb file into /live so that it uses the mastodon install of rails?

**Comment by impiaaa** [comment]
Oops, sorry, just saw this. You can put the script anywhere but it should be run from inside your Mastodon install.
